### ISSUE TITLE
How can I get the scaling values?

### ISSUE THREAD

**Issue by kllilizxc** [ssatguru/BabylonJS-EditControl#26]
Sorry if I missed it, I noticed you can use getPosition and getRotationQuaternion to get the position and rotation information, but how can I get the scaling ones?
What I want is to know the changed values in registered action listeners, since the only argument for the listener is the action type, so I have to get the values by other functions, am I right?

**Comment by ssatguru** [comment]
@kllilizxc 
getPosition and getRotationQuaternion provides the position and rotation information about the edit control not the mesh to which the edit control is "attached". Because the scale of the edit control  does not change there is no getScale method . You can of course check the scale of the mesh directly by using standard babylonjs API to get it scale. So use the action listener to find if the scale changed then query the mesh to get the scale.
